### ISSUE TITLE
MoneyServer.exe fails to start.

### ISSUE THREAD

**Issue by Moto** [BigManzai/OpenSim-DTL-NSL-Currency-2020#1]
Not sure why this has happen everything seems to be working correct other then when I launch moneyserver.exe.

I started in the proper order:
Robust.exe
MoneyServer.exe
OpenSim.exe

I never get a chance to load OpenSim.exe due to MoneyServer.exe crashing when started with nothing else to log then the error it reports.

Did I miss something? It just crash right when started and I'm pretty good at troubleshooting but this has left me clueless.

![MoneyServerStopped](https://user-images.githubusercontent.com/399415/77139172-fc35ee00-6a42-11ea-8d22-5d67786fe7b2.PNG)

**MoneyServer.ini**
[Startup]
;
; Place to create a PID file
; PIDFile = "/tmp/money.pid"

[MySql]
;
;Connection parameters of MySQL
hostname = REMOVEDFORSECURITY       ; Name of MySQL Server
database = money
username = root
password = REMOVEDFORSECURITY

pooling  = false
port = 3306

;
; Max DB connections kept by money server.
MaxConnection = 50

[MoneyServer]
;
; If the user is not found in database,he/she will be created with the default balance.
DefaultBalance = 0
 
;
; Is amount==0 transaction enable? Default is false.
EnableAmountZero = true

;
; If "00000000-0000-0000-0000-000000000000" is specified, all avatars can get money from system.
; If "" is specified, nobody can get money.
BankerAvatar = "1a9701d9-49aa-453d-af35-598d7e8d95f8"

;
; If you want to use llGiveMoney() function normally even when payer doesn't login to OpenSim,
; please set true to this valiable
EnableForceTransfer = true

;
; Send/Move money to/from avatar by Money Script 
;EnableScriptSendMoney = false
;MoneyScriptAccessKey  = "123456789"		;; Specify same secret key in include/config.php or WI(XoopenSim/Modlos)
;MoneyScriptIPaddress  = "202.26.159.139"	;; Not use 127.0.0.1. This is used to generate Script key

; 
; for HG/Guest Avatar. Foreign Avatar is always false
EnableHGAvatar = true
EnableGuestAvatar = true
HGAvatarDefaultBalance = 0
GuestAvatarDefaultBalance = 0

;
; Message that displayed in blue dialog, when balance is updated.
; If "" is specified, blue dialog is not displayed.
; You can use {0} and {1} in message string.
; {0} means amount and {1} means avatar name or object owner name.
BalanceMessageSendGift     = "Sent Gift L${0} to {1}."						;; for send gift to other avatar
BalanceMessageReceiveGift  = "Received Gift L${0} from {1}."				;; for receieve gift from other avatar
BalanceMessagePayCharge    = ""											;; for upload and group creation charge
BalanceMessageBuyObject    = "Bought the Object {2} from {1} by L${0}."	;; for buy the object
BalanceMessageSellObject   = "{1} bought the Object {2} by L${0}."         ;; for sell the object
BalanceMessageLandSale     = "Paid the Money L${0} for Land."				;; for buy the land
BalanceMessageScvLandSale  = ""											;; for get the money of the sold land
BalanceMessageGetMoney     = "Got the Money L${0} from {1}."				;; for get the money from object by llGiveMoney()
BalanceMessageBuyMoney     = "Bought the Money L${0}."						;; for buy the money from system
BalanceMessageRollBack     = "RollBack the Transaction: L${0} from/to {1}.";; when roll back ocuurred
BalanceMessageSendMoney    = "Paid the Money L${0} to {1}."				;; for sender of sending the money
BalanceMessageReceiveMoney = "Received L${0} from {1}."					;; for receive the money 

[Certificate]
;
; Certification Configuration
;

; CA Cert to check Client/Server Cert
;CACertFilename = "cacert.crt"

;
; HTTPS Server Cert (Server Mode)
;ServerCertFilename = "SineWaveCert.pfx"
;ServerCertPassword = "123"
;ServerCertFilename = "server_cert.p12"
;ServerCertPassword = ""

; Client Authentication from Region Server
;CheckClientCert = false						;; check Region Server
;ClientCrlFilename = "clcrl.crt"

;
; XML RPC to Region Server (Client Mode)
;;CheckServerCert = false						;; check Region Server
;;ClientCertFilename = "client_cert.p12"
;;ClientCertPassword = ""

**Comment by BigManzai** [comment]
Did you install mono?  https://www.mono-project.com/download/stable/
The precompiled are compiled on Ubuntu 19.
You will probably need to recompile for Windows.
Did you read the wiki?

 

# I have not tested Windows.

 

start testing please:
mono MoneyServer.exe or in Mono Prompt.

 

This Money Server is modified from DTL Currency and modified for Unix/Linux (It might work in MS Windows).
http://www.nsl.tuis.ac.jp/xoops/modules/xpwiki/?OpenSim%2FMoneyServer


 

mfg Manni

 

 


Gesendet: Freitag, 20. März 2020 um 06:41 Uhr
Von: "Greg Mott" <notifications@github.com>
An: BigManzai/OpenSim-DTL-NSL-Currency-2020 <OpenSim-DTL-NSL-Currency-2020@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [BigManzai/OpenSim-DTL-NSL-Currency-2020] MoneyServer.exe fails to start. (#1)


 

Not sure why this has happen everything seems to be working correct other then when I launch moneyserver.exe.

I started in the proper order:
Robust.exe
MoneyServer.exe
OpenSim.exe

I never get a chance to load OpenSim.exe due to MoneyServer.exe crashing when started with nothing else to log then the error it reports.

Did I miss something? It just crash right when started and I'm pretty good at troubleshooting but this has left me clueless.



MoneyServer.ini
[Startup]
;
; Place to create a PID file
; PIDFile = "/tmp/money.pid"

[MySql]
;
;Connection parameters of MySQL
hostname = REMOVEDFORSECURITY ; Name of MySQL Server
database = money
username = root
password = REMOVEDFORSECURITY

pooling = false
port = 3306

;
; Max DB connections kept by money server.
MaxConnection = 50

[MoneyServer]
;
; If the user is not found in database,he/she will be created with the default balance.
DefaultBalance = 0

;
; Is amount==0 transaction enable? Default is false.
EnableAmountZero = true

;
; If "00000000-0000-0000-0000-000000000000" is specified, all avatars can get money from system.
; If "" is specified, nobody can get money.
BankerAvatar = "1a9701d9-49aa-453d-af35-598d7e8d95f8"

;
; If you want to use llGiveMoney() function normally even when payer doesn't login to OpenSim,
; please set true to this valiable
EnableForceTransfer = true

;
; Send/Move money to/from avatar by Money Script
;EnableScriptSendMoney = false
;MoneyScriptAccessKey = "123456789" ;; Specify same secret key in include/config.php or WI(XoopenSim/Modlos)
;MoneyScriptIPaddress = "202.26.159.139" ;; Not use 127.0.0.1. This is used to generate Script key

;
; for HG/Guest Avatar. Foreign Avatar is always false
EnableHGAvatar = true
EnableGuestAvatar = true
HGAvatarDefaultBalance = 0
GuestAvatarDefaultBalance = 0

;
; Message that displayed in blue dialog, when balance is updated.
; If "" is specified, blue dialog is not displayed.
; You can use {0} and {1} in message string.
; {0} means amount and {1} means avatar name or object owner name.
BalanceMessageSendGift = "Sent Gift L${0} to {1}." ;; for send gift to other avatar
BalanceMessageReceiveGift = "Received Gift L${0} from {1}." ;; for receieve gift from other avatar
BalanceMessagePayCharge = "" ;; for upload and group creation charge
BalanceMessageBuyObject = "Bought the Object {2} from {1} by L${0}." ;; for buy the object
BalanceMessageSellObject = "{1} bought the Object {2} by L${0}." ;; for sell the object
BalanceMessageLandSale = "Paid the Money L${0} for Land." ;; for buy the land
BalanceMessageScvLandSale = "" ;; for get the money of the sold land
BalanceMessageGetMoney = "Got the Money L${0} from {1}." ;; for get the money from object by llGiveMoney()
BalanceMessageBuyMoney = "Bought the Money L${0}." ;; for buy the money from system
BalanceMessageRollBack = "RollBack the Transaction: L${0} from/to {1}.";; when roll back ocuurred
BalanceMessageSendMoney = "Paid the Money L${0} to {1}." ;; for sender of sending the money
BalanceMessageReceiveMoney = "Received L${0} from {1}." ;; for receive the money

[Certificate]
;
; Certification Configuration
;

; CA Cert to check Client/Server Cert
;CACertFilename = "cacert.crt"

;
; HTTPS Server Cert (Server Mode)
;ServerCertFilename = "SineWaveCert.pfx"
;ServerCertPassword = "123"
;ServerCertFilename = "server_cert.p12"
;ServerCertPassword = ""

; Client Authentication from Region Server
;CheckClientCert = false ;; check Region Server
;ClientCrlFilename = "clcrl.crt"

;
; XML RPC to Region Server (Client Mode)
;;CheckServerCert = false ;; check Region Server
;;ClientCertFilename = "client_cert.p12"
;;ClientCertPassword = ""

**Comment by BigManzai** [comment]
Caution! This is the first test.
Please test it.

https://github.com/BigManzai/OpenSim-DTL-NSL-Currency-2020/tree/master/binary/Windows

 

mfg. Manni

 
 

Gesendet: Freitag, 20. März 2020 um 06:41 Uhr
Von: "Greg Mott" <notifications@github.com>
An: BigManzai/OpenSim-DTL-NSL-Currency-2020 <OpenSim-DTL-NSL-Currency-2020@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [BigManzai/OpenSim-DTL-NSL-Currency-2020] MoneyServer.exe fails to start. (#1)


 

Not sure why this has happen everything seems to be working correct other then when I launch moneyserver.exe.

I started in the proper order:
Robust.exe
MoneyServer.exe
OpenSim.exe

I never get a chance to load OpenSim.exe due to MoneyServer.exe crashing when started with nothing else to log then the error it reports.

Did I miss something? It just crash right when started and I'm pretty good at troubleshooting but this has left me clueless.



MoneyServer.ini
[Startup]
;
; Place to create a PID file
; PIDFile = "/tmp/money.pid"

[MySql]
;
;Connection parameters of MySQL
hostname = REMOVEDFORSECURITY ; Name of MySQL Server
database = money
username = root
password = REMOVEDFORSECURITY

pooling = false
port = 3306

;
; Max DB connections kept by money server.
MaxConnection = 50

[MoneyServer]
;
; If the user is not found in database,he/she will be created with the default balance.
DefaultBalance = 0

;
; Is amount==0 transaction enable? Default is false.
EnableAmountZero = true

;
; If "00000000-0000-0000-0000-000000000000" is specified, all avatars can get money from system.
; If "" is specified, nobody can get money.
BankerAvatar = "1a9701d9-49aa-453d-af35-598d7e8d95f8"

;
; If you want to use llGiveMoney() function normally even when payer doesn't login to OpenSim,
; please set true to this valiable
EnableForceTransfer = true

;
; Send/Move money to/from avatar by Money Script
;EnableScriptSendMoney = false
;MoneyScriptAccessKey = "123456789" ;; Specify same secret key in include/config.php or WI(XoopenSim/Modlos)
;MoneyScriptIPaddress = "202.26.159.139" ;; Not use 127.0.0.1. This is used to generate Script key

;
; for HG/Guest Avatar. Foreign Avatar is always false
EnableHGAvatar = true
EnableGuestAvatar = true
HGAvatarDefaultBalance = 0
GuestAvatarDefaultBalance = 0

;
; Message that displayed in blue dialog, when balance is updated.
; If "" is specified, blue dialog is not displayed.
; You can use {0} and {1} in message string.
; {0} means amount and {1} means avatar name or object owner name.
BalanceMessageSendGift = "Sent Gift L${0} to {1}." ;; for send gift to other avatar
BalanceMessageReceiveGift = "Received Gift L${0} from {1}." ;; for receieve gift from other avatar
BalanceMessagePayCharge = "" ;; for upload and group creation charge
BalanceMessageBuyObject = "Bought the Object {2} from {1} by L${0}." ;; for buy the object
BalanceMessageSellObject = "{1} bought the Object {2} by L${0}." ;; for sell the object
BalanceMessageLandSale = "Paid the Money L${0} for Land." ;; for buy the land
BalanceMessageScvLandSale = "" ;; for get the money of the sold land
BalanceMessageGetMoney = "Got the Money L${0} from {1}." ;; for get the money from object by llGiveMoney()
BalanceMessageBuyMoney = "Bought the Money L${0}." ;; for buy the money from system
BalanceMessageRollBack = "RollBack the Transaction: L${0} from/to {1}.";; when roll back ocuurred
BalanceMessageSendMoney = "Paid the Money L${0} to {1}." ;; for sender of sending the money
BalanceMessageReceiveMoney = "Received L${0} from {1}." ;; for receive the money

[Certificate]
;
; Certification Configuration
;

; CA Cert to check Client/Server Cert
;CACertFilename = "cacert.crt"

;
; HTTPS Server Cert (Server Mode)
;ServerCertFilename = "SineWaveCert.pfx"
;ServerCertPassword = "123"
;ServerCertFilename = "server_cert.p12"
;ServerCertPassword = ""

; Client Authentication from Region Server
;CheckClientCert = false ;; check Region Server
;ClientCrlFilename = "clcrl.crt"

;
; XML RPC to Region Server (Client Mode)
;;CheckServerCert = false ;; check Region Server
;;ClientCertFilename = "client_cert.p12"
;;ClientCertPassword = ""

**Comment by Moto** [comment]
I always miss something simple thank you for the fast reply, I will be happy to help you with any testing both Windows builds or Mono builds.
